exports.up = function (knex) {
    return knex.schema
        .createTable("products", (table) => {
            table.increments("id").primary();
            table.string("name", 120).notNull();
            table.string("url_img", 120).notNull();

            table.integer("estoque_atual").notNull().defaultTo(0);
            table.integer("estoque_atual").notNull().defaultTo(0);
            table.integer("estoque_atual").notNull().defaultTo(0);

            table.string("img_1", 120)
            table.string("img_2", 120)
            table.string("img_3", 120)
            table.string("img_4", 120)

            table.float("price").notNull().defaultTo(0);
            table.float("price_promotion").notNull().defaultTo(0);
            table.boolean("promotion", 1).notNull().defaultTo(0);

            table.string("description")

            table.integer('id_category').unsigned().notNull().references('id').inTable('categories')

            table.boolean("disabled", 1).notNull().defaultTo(0);

            table.timestamp("updated_at").defaultTo(knex.raw("NULL ON UPDATE CURRENT_TIMESTAMP"));
            table.timestamp('created_at').defaultTo(knex.fn.now())
            table.timestamp("deleted_at").nullable();
        })
        .then(function () {
            return knex("products").insert([
                {
                    name: "Cama Londres Azul Chicxs",
                    url_img: "",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: false,
                    id_category: 1
                },
                {
                    name: "Bloco Cama solteiro Nórdica com bicama",
                    url_img: "https://www.mulherportuguesa.com/wp-content/uploads/2016/10/Significado-da-cor-preto.jpg",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: false,
                    id_category: 1
                },
                {
                    name: "CAMA ARTICULADA MOTORIZADA PILATI ZEUS - ESTRADO LIFE - CASAL, QUEEN E KING SIZE - SEM COLCHÃO",
                    url_img: "https://www.paisefilhos.ind.br/uploads/webp/e606d578f1b91c98c683a1888f33ed52.webp",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: false,
                    id_category: 1
                },
                {
                    name: "Fohu cama infantil de madeira de carvalho moderna, 3 unidades com cama com escadas cama de cobertura conjuntos de móveis",
                    url_img: "https://www.paisefilhos.ind.br/uploads/webp/e606d578f1b91c98c683a1888f33ed52.webp",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: false,
                    id_category: 1
                },
                {
                    name: "Brinquedo para banho animais marinhos",
                    url_img: "https://www.paisefilhos.ind.br/uploads/webp/e606d578f1b91c98c683a1888f33ed52.webp",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: true,
                    id_category: 2,
                    description: "- Feita com o tecido de microfibra semi-impermeável; - Design lindo; - Almofada fixa com a cama sem a possibilidade do Pet morde-la ou tira-la do lugar; - Uma cor linda para seu ambiente; - Evita mofos não junta ácaros e/ou fungos;"
                },
                {
                    name: "Brinquedos educativos",
                    url_img: "https://chiquititos.com.br/wp-content/uploads/2022/07/Pop-It-Fidget-Toy-Brinquedo-Anti-Stress-2022.png",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: true,
                    id_category: 2
                },
                {
                    name: "Brinquedos Educativos: Guia Completo por Idade (0 a 3 anos)",
                    url_img: "https://chiquititos.com.br/wp-content/uploads/2022/07/Brinquedo-Educativo-Cubo-Didatico-com-Blocos-Merco-Toys.png",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: false,
                    id_category: 2
                },
                {
                    name: "JOGO AÇO INOX TRAMONTINA COZINHA E MESA 7PÇS 64310/080",
                    url_img: "https://www.paisefilhos.ind.br/uploads/webp/e606d578f1b91c98c683a1888f33ed52.webp",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: true,
                    id_category: 4
                },
                {

                    name: "Cozinha Completa 100% MDF Modular Édez Uno, 6 Peças, Off White e Louro Freijó",
                    url_img: "https://www.taqi.com.br/file/general/conteudo-personalizado-taqi-cozinha-edez-uno-9999254014718-04.png",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: true,
                    id_category: 4
                },
                {
                    name: "Cadeira Epoxi Prata Para Cozinha Preto",
                    url_img: "https://cdn.leroymerlin.com.br/products/cadeira_epoxi_prata_para_cozinha__preto_1567179780_825f_600x600.png",
                    price: 295.9,
                    price_promotion: 266.31,
                    promotion: false,
                    id_category: 4
                },
                {
                    name: "Mouse Gamer Sem Fio Logitech, 6 Botões Programáveis, Compatível com Windows, macOS, iPadOS, iOS",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                },
                {
                    name: "Mouse Gamer Sem Fio Logitech, 6 Botões Programáveis, Compatível com Windows, macOS, iPadOS, iOS",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/31QcZNzTb-L._AC_UL320_.jpg",
                },
                {
                    name: "Teclado gamer para computador pc teclado semi mecanico Abnt2 com luz de led rgb para Ps4 Ps5 Xbox On...",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/81wbZbfXumL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/81wbZbfXumL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/81wbZbfXumL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/81wbZbfXumL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/81wbZbfXumL._AC_UL320_.jpg",
                },
                {
                    name: "Mouse Gamer S/ Fio Logitech LIGHTSPEED com 6 Botões Programáveis e Até 12.000 DPI - Lilás + Headset ...",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/31VLP4-usaL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/31VLP4-usaL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/31VLP4-usaL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/31VLP4-usaL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/31VLP4-usaL._AC_UL320_.jpg",
                },
                {
                    name: "KABEWUS Suporte para laptop para mesa suporte estável para suporte ergonômico alumínio para 12-17 po...",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61iqcAJbR1L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61iqcAJbR1L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61iqcAJbR1L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61iqcAJbR1L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61iqcAJbR1L._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer OnGaming Core i5 10400F, GeForce GTX 1660 6GB, 16GB Ram, SSD 480GB, Gabinete Gamer",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61PCu089lXL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61PCu089lXL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61PCu089lXL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61PCu089lXL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61PCu089lXL._AC_UL320_.jpg",
                },
                {
                    name: "PC GAMER AMD RYZEN 5 5600G 16GB (RADEON VEGA 7 INTEGRADO) SSD 480GB, 500W 80 PLUS, NEOLOGIC - NLI84302",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61vtqwiaSXL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61vtqwiaSXL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61vtqwiaSXL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61vtqwiaSXL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61vtqwiaSXL._AC_UL320_.jpg",
                },
                {
                    name: "Cpu I3 4gb SSD 240gb *10X MAIS RÁPIDO*",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61H19XmKXEL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61H19XmKXEL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61H19XmKXEL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61H19XmKXEL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61H19XmKXEL._AC_UL320_.jpg",
                },
                {
                    name: "Mini Desktop PC Qcta-Core i9 9880H, Windows 11 Mini Computador, 16GB DDR4 RAM 512GB NVME SSD, UHD Gráficos",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51WVx-9UuKL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51WVx-9UuKL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51WVx-9UuKL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51WVx-9UuKL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51WVx-9UuKL._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer AMD A8-9600, 32GB RAM DDR4, SSD 480GB, Vídeo Radeon R7, Gabinete com LED + Mouse Gamer de Brinde",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/6116yZ36dJL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/6116yZ36dJL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/6116yZ36dJL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/6116yZ36dJL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/6116yZ36dJL._AC_UL320_.jpg",
                },
                {
                    name: "PC CPU Intel Core I5, 8GB DE Memória ram, Ssd 240GB",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/512WCabCRyL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/512WCabCRyL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/512WCabCRyL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/512WCabCRyL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/512WCabCRyL._AC_UL320_.jpg",
                },
                {
                    name: "PC INTEL I5 3470, 8GB DDR3, SSD 240GB LOL - FREEFIRE",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51+E4635GQS._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51+E4635GQS._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51+E4635GQS._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51+E4635GQS._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51+E4635GQS._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer OnGaming Core i7 11700KF, GeForce RTX 3060 12GB, 16GB Ram, SSD M.2 NVMe 500GB, 11ª Geração",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61KPkz0EcWL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61KPkz0EcWL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61KPkz0EcWL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61KPkz0EcWL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61KPkz0EcWL._AC_UL320_.jpg",
                },
                {
                    name: "PC GAMER RYZEN 5 3600 16GB (RTX 2060 6GB) SSD 240GB 500W, NEOLOGIC - NLI84372",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61hwANlzjzL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61hwANlzjzL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61hwANlzjzL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61hwANlzjzL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61hwANlzjzL._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer OnGaming Core i5 10400F, GeForce GTX 1650 4GB, 16GB Ram, SSD NVMe 500GB",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer Start Login AMD Athlon 3000G 3.5GHz SSD 240Gb Mem 8Gb DDR4 3200MHz Linux",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer ITX Arena, Core i5 10400F, GTX 1650 4GB, 16GB, SSD M.2 250GB, Gabinete Gamer",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61i-0HPiu7L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61i-0HPiu7L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61i-0HPiu7L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61i-0HPiu7L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61i-0HPiu7L._AC_UL320_.jpg",
                },
                {
                    name: "Mini Pc Beelink Gk35 128gb Ssd 8gb Ram Processador Intel Celeron J4205 Sistema Operacional Windows 10 Pro",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51B6I7w34fL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51B6I7w34fL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51B6I7w34fL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51B6I7w34fL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51B6I7w34fL._AC_UL320_.jpg",
                },
                {
                    name: "Pc Cpu Gamer 4ª geração para Free Fire SSD + WIFI Novo c/NF",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/31lBG7HK4XL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/31lBG7HK4XL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/31lBG7HK4XL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/31lBG7HK4XL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/31lBG7HK4XL._AC_UL320_.jpg",
                },
                {
                    name: "Computador Completo Intel Core i7 4 Núcleos Super Turbo 16GB SSD 256GB Monitor 19 Pc Hdmi Teclado e Mouse Strong Tech",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/71LoUPTNEQL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/71LoUPTNEQL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/71LoUPTNEQL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/71LoUPTNEQL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/71LoUPTNEQL._AC_UL320_.jpg",
                },
                {
                    name: "Pc Gamer Intel Core i5 10400F - 4.30 GHz, 16GB RAM Gamer DDR4, Nvidia 4GB, SSD 512GB, Fonte 500w, Gabinete",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/41LrpIzVIOL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/41LrpIzVIOL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/41LrpIzVIOL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/41LrpIzVIOL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/41LrpIzVIOL._AC_UL320_.jpg",
                },
                {
                    name: "HEYSTOP Switch Case Compatível com Nintendo Switch, 9 em 1 Switch Acessórios com 8 Bolsa de Transpor...",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/81fu1Gei7VL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/81fu1Gei7VL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/81fu1Gei7VL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/81fu1Gei7VL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/81fu1Gei7VL._AC_UL320_.jpg",
                },
                {
                    name: "HD Externo Portátil 1TB UnionSine Disco Rígido compatível Mac/Pc/Notebook/PS4 - USB 3.0-HD2510",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61b37oBFdoL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61b37oBFdoL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61b37oBFdoL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61b37oBFdoL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61b37oBFdoL._AC_UL320_.jpg",
                },
                {
                    name: "Headset Gamer Sem Fio Logitech G935 7.1 Dolby Surround, RGB LIGHTSYNC, Drivers de Áudio Avançado par...",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/71FkbQzfOYL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/71FkbQzfOYL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/71FkbQzfOYL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/71FkbQzfOYL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/71FkbQzfOYL._AC_UL320_.jpg",
                },
                {
                    name: "WB Capa com Teclado Para Tablet Samsung Galaxy Tab S7 FE 12.4 Polegadas Couro Preto com duração de ...",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61pNE242-1L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61pNE242-1L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61pNE242-1L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61pNE242-1L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61pNE242-1L._AC_UL320_.jpg",
                },
                {
                    name: "PC CPU Mancer Home Office, Intel Core I5, 8GB DDR3, SSD 240GB",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51taC5D8jZL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51taC5D8jZL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51taC5D8jZL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51taC5D8jZL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51taC5D8jZL._AC_UL320_.jpg",
                },
                {
                    name: "Pc Gamer I7 3770+16gb Ram+hd 1tb+pl.vi 4g+f.500w+monitor 19",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61E7bL44ZDL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61E7bL44ZDL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61E7bL44ZDL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61E7bL44ZDL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61E7bL44ZDL._AC_UL320_.jpg",
                },
                {
                    name: "PC CPU Mancer, AMD Ryzen 3 3200G, Vega 8, 8GB de Ram DDR4, SSD 240GB, Fonte 500W",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer OnGaming Core i3 10100F, GeForce GTX 1050 Ti 4GB, 8GB Ram, SSD 240GB, Gabinete Gamer",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/71zucbJyaVL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/71zucbJyaVL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/71zucbJyaVL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/71zucbJyaVL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/71zucbJyaVL._AC_UL320_.jpg",
                },
                {
                    name: "MINI PC ACCEPT 2K V3 INTEL CELERON QC J4105/ 4GB/ SSD 240GB/ VESA/LINUX",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/41DzGAjpQxL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/41DzGAjpQxL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/41DzGAjpQxL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/41DzGAjpQxL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/41DzGAjpQxL._AC_UL320_.jpg",
                },
                {
                    name: "PC CPU Mancer Home,Intel Core I7, 8GB DE RAM, HD 500GB + SSD 240GB",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                },
                {
                    name: "Pc Computador intel i3-10100, 8gb Ddr4, Ssd 120gb, 500w",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/512-eEqebFL._AC_UL320_.jpg",
                },
                {
                    name: "PC CPU Mancer, ADM Ryzen 3 3200G, Vega 8, 16GB De Memória Ram DDR4, SSD 240GB, Fonte 500W",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61y1nUUpvkL._AC_UL320_.jpg",
                },
                {
                    name: "Computador Completo Kit Gamer Pc Intel Core i3 4GB SSD 120GB Monitor 19 Cpu Hdmi Strong Tech",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/71mgdOT40UL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/71mgdOT40UL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/71mgdOT40UL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/71mgdOT40UL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/71mgdOT40UL._AC_UL320_.jpg",
                },
                {
                    name: "Pc Gamer G-fire Htg-718 Amd Ryzen 5 5600g 8gb (radeon Graphics 2gb) M.2 Nvme 256gb 500w",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/41djMPw3slL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/41djMPw3slL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/41djMPw3slL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/41djMPw3slL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/41djMPw3slL._AC_UL320_.jpg",
                },
                {
                    name: "Computador Pc Completo Intel Core i3 8GB HD 500GB Wi-fi",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51vnJvGTOVL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51vnJvGTOVL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51vnJvGTOVL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51vnJvGTOVL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51vnJvGTOVL._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer Login AMD Ryzen 5 5600G 3.9GHz SSD 512Gb 8Gb DDR4 3200MHz Linux",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/41EB5IE-xbL._AC_UL320_.jpg",
                },
                {
                    name: "Pc Computador CPU MINI Dual Core / 8GB Ram/SSD 240GB - LIQUIDAÇÃO",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/41QR44s0sXL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/41QR44s0sXL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/41QR44s0sXL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/41QR44s0sXL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/41QR44s0sXL._AC_UL320_.jpg",
                },
                {
                    name: "Beelink Mini PC T4 Pro, Celeron N3350 até 2,4 GHz, mini computador desktop 4 GB DDR + 64 GB, PC pequeno suporta",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61DxiuVKN+L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61DxiuVKN+L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61DxiuVKN+L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61DxiuVKN+L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61DxiuVKN+L._AC_UL320_.jpg",
                },
                {
                    name: "PC HOME/I7 3770/H61/16GB DDR3/SSD 240GB/GABINETE ATX/200W/WIFI-LIDER 007",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51ktqmk-jzL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51ktqmk-jzL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51ktqmk-jzL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51ktqmk-jzL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51ktqmk-jzL._AC_UL320_.jpg",
                },
                {
                    name: "Computador Intel Core i5 Com Hdmi 8GB HD 1TB Windows 10 Teclado Mouse Desktop Pc",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61l2D5a90-L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61l2D5a90-L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61l2D5a90-L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61l2D5a90-L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61l2D5a90-L._AC_UL320_.jpg",
                },
                {
                    name: "Computador Pc Completo i5 3° Geração 8gb Hd 500GB + Wi-fi",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/41peWzcW9IL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/41peWzcW9IL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/41peWzcW9IL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/41peWzcW9IL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/41peWzcW9IL._AC_UL320_.jpg",
                },
                {
                    name: "PC GAMER INTEL I5 16GB (RX 550 2GB) SSD 120GB 500W, SMART PC - SMT84326",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                },
                {
                    name: "Pc Gamer Completo Hércules Intel i3 3º Ger. GT 730 8GB HD 500GB Wi-fi",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51rG8+ZUD9L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51rG8+ZUD9L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51rG8+ZUD9L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51rG8+ZUD9L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51rG8+ZUD9L._AC_UL320_.jpg",
                },
                {
                    name: "COMPUTADOR BUSINESS B100 - CELERON DUAL CORE J1800 2.41GHZ 4GB DDR3 SODIMM HD 500GB 2 SERIAL 1 PARALELA FONTE 200W",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/71slGzoMT9L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/71slGzoMT9L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/71slGzoMT9L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/71slGzoMT9L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/71slGzoMT9L._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer OnGaming AMD Ryzen 5 4650G, Radeon Graphics Vega 7, 16GB Ram, SSD 240GB, 500W",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/71Cc5rM5LTL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/71Cc5rM5LTL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/71Cc5rM5LTL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/71Cc5rM5LTL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/71Cc5rM5LTL._AC_UL320_.jpg",
                },
                {
                    name: "Mini PC Stick Intel Celeron N4000 (até 2,6 GHz), Windows 10 Pro, Mini Stick de 4 GB DDR4 64 GB eMMC Micro Desktop",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61l8yh+AzgL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61l8yh+AzgL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61l8yh+AzgL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61l8yh+AzgL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61l8yh+AzgL._AC_UL320_.jpg",
                },
                {
                    name: "Computador Intel Core i7 4 Núcleos Super Turbo 16GB SSD 256GB Pc Hdmi Strong Tech",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/719eCcq3hVL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/719eCcq3hVL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/719eCcq3hVL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/719eCcq3hVL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/719eCcq3hVL._AC_UL320_.jpg",
                },
                {
                    name: "Computador Pc Intel Core i7 4GB SSD 120GB Hdmi Cpu Desktop Strong Tech",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61PZfkb5sSL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61PZfkb5sSL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61PZfkb5sSL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61PZfkb5sSL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61PZfkb5sSL._AC_UL320_.jpg",
                },
                {
                    name: "PC Gamer OnGaming Core i7 12700K, GeForce RTX 3070Ti 8GB, 32GB Ram, SSD M.2 NVMe 512GB, 12ª Geraçao",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/71RWzcC10oL._AC_UL320_.jpg",
                },
                {
                    name: "PC GAMER MANCER (INTEL CORE I5, GTX 1650 4GB, 8GB DDR3, SSD 240GB, 500W)",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51kjY+v6k7L._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51kjY+v6k7L._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51kjY+v6k7L._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51kjY+v6k7L._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51kjY+v6k7L._AC_UL320_.jpg",
                },
                {
                    name: "Computador Pc Completo Intel i5 4°Geração 8gb SSD 240GB Wi-fi",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51Y4OVKTiWL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51Y4OVKTiWL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51Y4OVKTiWL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51Y4OVKTiWL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51Y4OVKTiWL._AC_UL320_.jpg",
                },
                {
                    name: "Mini PC para Windows 10 Home, Mini Computador 8GB LPDDR4 128GB M.2 2242 SSD para Celeron J4125 Quad Core, Suporte",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/614MiWBZjwL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/614MiWBZjwL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/614MiWBZjwL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/614MiWBZjwL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/614MiWBZjwL._AC_UL320_.jpg",
                },
                {
                    name: "PC GAMER INTEL I5 8GB (RX 550 2GB) SSD 240GB 500W, SMART PC - SMT84324",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51A1iOwc-pL._AC_UL320_.jpg",
                },
                {
                    name: "Pc Gamer Smart Pc SMT81284 Intel i5 8GB (GeForce GTX 1650 4GB) 1TB",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51mHQApnidL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51mHQApnidL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51mHQApnidL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51mHQApnidL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51mHQApnidL._AC_UL320_.jpg",
                },
                {
                    name: "Cpu I3 4gb SSD 240gb *20X MAIS RÁPIDO*",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/41Us-KCnFkL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/41Us-KCnFkL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/41Us-KCnFkL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/41Us-KCnFkL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/41Us-KCnFkL._AC_UL320_.jpg",
                },
                {
                    name: "Pc Gamer Intel Core i7, 16GB RAM, GT 1030 2GB, HD 1000GB, Fonte 500w, Gabinete com RGB",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51EOnkZKQSL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51EOnkZKQSL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51EOnkZKQSL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51EOnkZKQSL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51EOnkZKQSL._AC_UL320_.jpg",
                },
                {
                    name: "Microfone Condensador USB Blue Snowball iCE com Captação Cardióide, Suporte Ajustável, Conexão Plug ...",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61GwlnuqZQL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61GwlnuqZQL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61GwlnuqZQL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61GwlnuqZQL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61GwlnuqZQL._AC_UL320_.jpg",
                },
                {
                    name: "KABEWUS Expansor Hub Usb 3.0 PD carga rápida 5 em 1 Conector de conversão typec multi-porta doca de ...",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51gkMFiOKXL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51gkMFiOKXL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51gkMFiOKXL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51gkMFiOKXL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51gkMFiOKXL._AC_UL320_.jpg",
                },
                {
                    name: "Cockpit Simulador Suporte Para Volante X Retrátil V3 Preto Extreme Simracing",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/51snxQIKQfL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/51snxQIKQfL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/51snxQIKQfL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/51snxQIKQfL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/51snxQIKQfL._AC_UL320_.jpg",
                },
                {
                    name: "Teclado Mecânico Gamer Logitech G713 RGB LIGHTSYNC Com Switch GX Brown Tactile",
                    price: 2,
                    price_promotion: 1,
                    promotion: false,
                    id_category: 1,
                    url_img: "https://m.media-amazon.com/images/I/61VWTUZPusL._AC_UL320_.jpg",
                    img_1: "https://m.media-amazon.com/images/I/61VWTUZPusL._AC_UL320_.jpg",
                    img_2: "https://m.media-amazon.com/images/I/61VWTUZPusL._AC_UL320_.jpg",
                    img_3: "https://m.media-amazon.com/images/I/61VWTUZPusL._AC_UL320_.jpg",
                    img_4: "https://m.media-amazon.com/images/I/61VWTUZPusL._AC_UL320_.jpg",
                }
            ]);
        });
};

exports.down = function (knex) {
    return knex.schema.dropTable("products");
};
